SM:AddTab("General Settings")
SM:NumberInput("Bank PIN", "bankPin", 1111, 0, 9999)
SM:Dropdown("Rune Type", "runeType", {"flesh","spirit","bone","miasma","air", "water", "earth", "fire", "mind", "body", "nature", "astral", "cosmic", "blood", "chaos", "law", "death", "soul", "time"}, "air")
SM:Dropdown("Teleport method", "teleportMethod", {"War's Retreat Teleport","GotE Deep Sea Fishing Hub"}, "War's Retreat Teleport")
SM:Checkbox("Access to Altar of War?", "hasAccessToAltarOfWar", false)
SM:Dropdown("Soul Altar Charges", "soulAltarCharges", {"full 100 charges", "1 inventory worth of charges", "1 charge"}, "full 100 charges")
SM:Checkbox("Abyssal parasite?", "hasAbyssalParasite", false)
SM:Checkbox("Abyssal lurker?", "hasAbyssalLurker", false)
SM:Checkbox("Abyssal titan?", "hasAbyssalTitan", false)